var Navigation = new global.mongoose.Schema({
	_id: global.mongoose.Schema.ObjectId,
	nId: String,
        vId: String,
        VrId: String,
        sId: Number,
        aId: Number,
	screenWidth: Number,
	screenHeight: Number,
	viewpointWidth: Number,
	viewpointHeight: Number,
	viewpointWidthIE6: Number,
	viewpointHeightIE6: Number,
	viewpointWidthIE: Number,
	viewpointHeightIE: Number,
	outerWidth: Number,
	outerHeight: Number,
        pageXOffset: Number,
        pageYOffset: Number,
        screenX: Number,
        screenY: Number,
	referer: String,
	currentURL: String,
	locationHREF: String,
	locationHash: String,
	locationHost: String,
	locationHostName: String,
	locationPathName: String,
	locationPort: String,
	locationProtocol: String,
	locationSearch: String,
	documentMode: String,
	pageTitle: String,
	readyState: String,
	lastModified: String,
	timestamp: Date,
        link: Boolean,
        formSubmit: Boolean,
        target: String,
        elementId: String,
        elementTitle: String,
        targetWindow: String,
        dateCreated: Date
});

Navigation.index({ nId: 1, vId: 1, VrId: 1, sId: 1, aId: 1 }, { unique: true });

module.exports = global.mongoose.model('Navigation', Navigation);